//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenSharp.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LtgSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LtgSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZenSharp.Core.Tests.LtgSamples", typeof(LtgSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This is the house that Jack built.
        ///// This is the cheese that lay in the house that Jack built.
        ///// This is the rat that ate the cheese
        ///// That lay in the house that Jack built.
        ///
        ///tjb      ::= &quot;that Jack built&quot;=tjb
        ///thisis   ::= &quot;This is the&quot;=tit
        ///s        ::= &quot; &quot;
        ///sentence ::= $sencence par=&quot;value&quot; par2=&quot;sample&quot; $
        ///sep      ::= &quot;-&quot;
        ///
        ///scope &quot;house&quot; {
        ///  base  ::= thisis s sentence
        ///  start ::= base | base sep tjb
        ///}
        ///.
        /// </summary>
        internal static string jack {
            get {
                return ResourceManager.GetString("jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// Sample file
        ///space ::= &quot; &quot;
        ///
        ///// Resharper macros
        ///cursor ::= &quot;$END$&quot;
        ///manualType ::= &quot;$type$&quot;
        ///
        ///// Fields
        ///field ::= accessField &quot;&quot;=f space type &quot;$name$&quot; &quot;;&quot;
        ///
        ///identifier ::= $name macros = &quot;contant(&quot;&quot;name&quot;&quot;)&quot;$
        ///
        ///// Methods
        ///method       ::= accessMethod methodDecl space manualType space methodName &quot;(&quot; cursor &quot;){}&quot;
        ///methodname   ::=  &quot;$name$&quot; | identifier
        ///methodDecl   ::= space static=M | &quot;&quot;=m
        ///accessMethod ::= &quot;public&quot; | private=_ | protected=pr
        ///
        ///// Auto properties
        ///property        ::= accessPr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
    }
}
